--------------------------------------------------------
-- Archivo creado  - martes-julio-02-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_CUENTAS
--------------------------------------------------------

  CREATE TABLE "T_CUENTAS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1001 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
      "TITLE" VARCHAR2(80 BYTE), 
      "CUENTA_RUBRO_ID" NUMBER, 
      "CUENTA_NUMERO" NUMBER, 
      "CUENTA_TIPO" VARCHAR2(20 BYTE),
      "BLOQ_DESDE" DATE,
      "BLOQ_HASTA" DATE
   ) ;
--------------------------------------------------------
--  DDL for Index T_CUENTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T_CUENTAS_PK" ON "T_CUENTAS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index T_CUENTAS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "T_CUENTAS_UK1" ON "T_CUENTAS" ("CUENTA_RUBRO_ID", "CUENTA_NUMERO") 
  ;
--------------------------------------------------------
--  Constraints for Table T_CUENTAS
--------------------------------------------------------

  ALTER TABLE "T_CUENTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "T_CUENTAS" ADD CONSTRAINT "T_CUENTAS_PK" PRIMARY KEY ("ID")
  USING INDEX "T_CUENTAS_PK"  ENABLE;
  ALTER TABLE "T_CUENTAS" ADD CONSTRAINT "T_CUENTAS_UK1" UNIQUE ("CUENTA_RUBRO_ID", "CUENTA_NUMERO")
  USING INDEX "T_CUENTAS_UK1"  ENABLE;
  ALTER TABLE "T_CUENTAS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "T_CUENTAS" MODIFY ("CUENTA_RUBRO_ID" NOT NULL ENABLE);
  ALTER TABLE "T_CUENTAS" MODIFY ("CUENTA_NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_CUENTAS
--------------------------------------------------------

  ALTER TABLE "T_CUENTAS" ADD CONSTRAINT "T_CUENTAS_FK1" FOREIGN KEY ("CUENTA_RUBRO_ID")
	  REFERENCES "T_CUENTA_RUBROS" ("ID") ENABLE;
