--------------------------------------------------------
--  DDL for Table T_PC_CUENTAS
--------------------------------------------------------

  CREATE TABLE "T_PC_CUENTAS" 
   (	"ID" NUMBER PRIMARY KEY NOT NULL,
      "PC_RUBRO_ID" NUMBER NOT NULL, 
      "PC_CUENTA_NUM" NUMBER NOT NULL, 
      "DETALLE" VARCHAR2(80 BYTE) NOT NULL, 
      "CUENTA_TIPO_KEY" VARCHAR2(20 BYTE),
      "BLOQ_DESDE" DATE,
      "BLOQ_HASTA" DATE
   ) ;

  CREATE UNIQUE INDEX "T_PC_CUENTAS_UK" ON "T_PC_CUENTAS" ("PC_RUBRO_ID", "PC_CUENTA_NUM");

  ALTER TABLE "T_PC_CUENTAS" ADD CONSTRAINT "T_PC_CUENTAS_FK1" FOREIGN KEY ("PC_RUBRO_ID") REFERENCES "T_PC_RUBROS" ("ID") ENABLE;

  CREATE OR REPLACE VIEW V_PC_CUENTAS AS
  SELECT ID
    ,PC_RUBRO_ID
    ,PC_CUENTA_NUM
    ,DETALLE
    ,CUENTA_TIPO_KEY
    ,BLOQ_DESDE
    ,BLOQ_HASTA
    ,TO_CHAR(PC_RUBRO_ID,'000') || TO_CHAR(PC_CUENTA_NUM,'000') || ' ' || DETALLE TITLE
  FROM T_PC_CUENTAS;

  