CREATE TABLE T_COMPRAS_PAGOS (
    ID NUMBER(6, 0) NOT NULL ENABLE,
    CBTEFCH DATE,
    PROVEDOR_ID NUMBER(4, 0),
    DFISCAL_ID NUMBER,
    DOCNRO NUMBER(*, 0),
    IMPTOTAL NUMBER(10, 2),
    OBS VARCHAR2(80),
    CTA NUMBER,
    STATUS NUMBER,
    CREATED DATE,
    CREATED_BY VARCHAR2(20),
    UPDATED DATE,
    UPDATED_BY VARCHAR2(20),
    BLOCKED DATE,
    BLOCKED_BY VARCHAR2(20),
    CONSTRAINT compras_PAGOS_PK PRIMARY KEY (ID) USING INDEX ENABLE,
    CONSTRAINT compras_PAGOS_FK01 FOREIGN KEY (PROVEDOR_ID) REFERENCES T_PROVS (ID) ENABLE,
    CONSTRAINT compras_PAGOS_FK03 FOREIGN KEY (DFISCAL_ID) REFERENCES T_DFISCALES (ID) ENABLE
);
/

CREATE SEQUENCE COMPRAS_PAGOS_SEQ START WITH 1000 NOCACHE;

/

CREATE OR REPLACE TRIGGER "T_COMPRAS_PAGOS_TRG" BEFORE INSERT ON "T_COMPRAS_PAGOS" 
  FOR EACH ROW 
BEGIN 
    :NEW.CREATED    :=SYSDATE;
    :NEW.CREATED_BY := NVL(V('APP_USER'),USER);
    :NEW.STATUS := 1;
    :new.cta := 1;
    IF :NEW.ID IS NULL THEN
      SELECT COMPRAS_PAGOS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
END;

/
CREATE OR REPLACE TRIGGER "T_COMPRAS_PAGOS_TRG2" BEFORE UPDATE ON "T_COMPRAS_PAGOS" 
  FOR EACH ROW 
BEGIN 

  :NEW.UPDATED    :=SYSDATE;
  :NEW.UPDATED_BY := NVL(V('APP_USER'),USER);

  IF :new.status = 3 then
        :new.BLOCKED := sysdate;
        :new.BLOCKED_by := nvl(v('APP_USER'),USER);      
  end if;

  select sum(DOC_IMPORTE) into :NEW.IMPTOTAL from t_docs where COMPRAS_PAGO_ID = :new.id;


END;