CREATE OR REPLACE FORCE EDITIONABLE VIEW "LOA"."V_COMPRAS_CBTE" AS
    SELECT
        ID,
        CBTEFCH,
        CBTETIPO_ID,
        (SELECT KEY || ' ' || TO_CHAR(PTOVTA,'0000') || '-' || TO_CHAR(DOCNRO,'00000000') FROM T_CBTE_TIPOS WHERE ID = CBTETIPO_ID) TITLE,
        CONCEPTO_ID,
        DOCNRO,
        PTOVTA,
        SIGNO,
        CTA,
        PROVEDOR_ID,
        DFISCAL_ID,
        CUIT,
        PC_CUENTA_ID,
        PC_MES,
        IMPTOTCONC,
        IMPNETO,
        IMPOPEX,
        IMPTRIB,
        IMPIVA,
        IMPTOTAL,
        OBS,
        STATUS
    FROM
        T_COMPRAS_CBTES;

/

CREATE OR REPLACE FORCE EDITIONABLE VIEW "LOA"."V_COMPRAS_ITEMS" AS
    SELECT
        ID,
        CBTE_ID,
        ARTICULO_ID,
        (SELECT CODIGO FROM T_ARTICULOS WHERE ID = ARTICULO_ID ) ARTICULOS_TITLE,
        DETALLE,
        CANTIDAD,
        PRECIO,
        NETO,
        IVATIPOID,
        IVA,
        NETO + IVA SUBTOTAL,
        (SELECT CASE STATUS WHEN 3 THEN 'LOCK' ELSE 'ED' END
            FROM T_COMPRAS_CBTES WHERE ID = CBTE_ID ) LOCK_ROW
    FROM
        T_COMPRAS_ITEMS;

/

CREATE OR REPLACE FORCE EDITIONABLE VIEW "LOA"."V_COMPRAS_TRIBS" AS
    SELECT
        ID,
        CBTE_ID,
        TRIBUTOTIPOID,
        VALOR
    FROM
        T_COMPRAS_TRIBS;

/
select PROVEDOR_ID,sum(IMPTOTAL*SIGNO) 
    FROM T_COMPRAS_CBTES
    GROUP BY PROVEDOR_ID;