---
# ====== Application: PTC2023 ================================
id: 100
identification: 
  name: PTC2023
  alias: PTC2023
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: false
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 2005178322195559

authorization: 
  authorization-scheme: Must Not Be Public User
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled
  maximum-session-length: 21600
  maximum-session-idle-time: 10800
  session-timeout-warning: 600

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: PTC

globalization: 
  primary-language: English (United States) (en-us)
  document-direction: Left-To-Right
  language-derived-from: Application Preference (use FSP_LANGUAGE_PREFERENCE)
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DD-MM-YYYY
  date-time: 'DD-MM-YYYY HH24:MI:SS'
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image
  image-url: '#WORKSPACE_FILES#img/logo_torcoletti.png'

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Eventos

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-addActions
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 2005941089195570

navigation-bar: 
  implementation: List
  list: Navigation Bar # 2289738478196276
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: PTC2023

component-settings: 
- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 1468337589383808
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 281957163

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 1488940936912139
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 299643971

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 1489248152912140
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 299643972

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 1489580509912140
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 299643972

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 2002123946195545
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 2002468934195548
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 2002762159195548
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 2003023574195548
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 2003306649195550
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 2003648135195550
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 2003907111195550
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_IR ========================
  id: 2004267969195550
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 2004561900195550
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 1

- # ====== Component Setting: PLUGIN_COM.JK64.REPORT_GOOGLE_MAP_
  id: 3652310685825373
  identification: 
    name: PLUGIN_COM.JK64.REPORT_GOOGLE_MAP_R1
    type: Region

  subscription: 
    version-number: 1

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 2295637560196373
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  subscription: 
    version-number: 1

  configuration: 
    build-option: 'Feature: Feedback' # 2292314223196320

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 2295922450196376
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ALL_USERS
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 1

  configuration: 
    build-option: 'Feature: Access Control' # 2292114188196320

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

