CREATE OR REPLACE PACKAGE PLAN_CUENTAS_PKG AS

    FUNCTION CUENTA_TO_STRING (p_cuenta_id number) return varchar2;
    FUNCTION CUENTA_TITLE (p_cuenta_id number) return varchar2;

    FUNCTION RAMA_PRINCIPAL RETURN LIST_TREE;

    FUNCTION CUENTA_TIPOS RETURN LIST_BY_KEY;

    PROCEDURE AGREGAR_RUBRO(
        P_PARENT_ID INTEGER,
        P_RUBRO_TITLE VARCHAR2,
        P_CUENTA_TIPO VARCHAR2 DEFAULT NULL,
        P_RUBRO_ID OUT NUMBER
    );

    FUNCTION SIGUIENTE_RUBRO_ID(
        P_PARENT_ID INTEGER
    ) RETURN NUMBER;

    PROCEDURE AGREGAR_CUENTA(
        P_CUENTA_RUBRO_ID INTEGER,
        P_TITLE VARCHAR2,
        P_CUENTA_TIPO VARCHAR2,
        P_CUENTA_ID OUT NUMBER,
        P_CUENTA_NUMERO OUT NUMBER
    );

    FUNCTION SIGUIENTE_CUENTA_NUM(
        P_CUENTA_RUBRO_ID INTEGER
    ) RETURN NUMBER;

END PLAN_CUENTAS_PKG;