create or replace PACKAGE PLAN_DE_CUENTAS_PKG AS

    FUNCTION RAMA_PRINCIPAL RETURN LIST_TREE;
    FUNCTION LOV_CUENTA_CONFIG RETURN LIST_BY_KEY;

    FUNCTION SIGUIENTE_RUBRO_ID(
        P_PARENT_ID INTEGER
    ) RETURN NUMBER;

    PROCEDURE AGREGAR_RUBRO(
        P_PARENT_ID INTEGER,
        P_RUBRO_TITLE VARCHAR2,
        P_RUBRO_CONFIG VARCHAR2,
        P_RUBRO_ID IN OUT NUMBER
    );

    PROCEDURE EDITAR_RUBRO(
        P_RUBRO_ID INTEGER,
        P_RUBRO_TITLE VARCHAR2,
        P_RUBRO_CONFIG VARCHAR2
    );

    PROCEDURE BORRAR_RUBRO(
        P_RUBRO_ID INTEGER
    );

    FUNCTION SIGUIENTE_CUENTA_NUM(
        P_RUBRO_ID INTEGER
    ) RETURN NUMBER;

    PROCEDURE AGREGAR_CUENTA(
        P_RUBRO_ID INTEGER,
        P_CUENTA_NUM IN OUT NUMBER,
        P_CUENTA_TITLE VARCHAR2,
        P_CUENTA_CONFIG VARCHAR2,
        P_CUENTA_ID OUT NUMBER
    );

    PROCEDURE EDITAR_CUENTA(
        P_CUENTA_ID INTEGER,
        P_CUENTA_NUM NUMBER,
        P_CUENTA_TITLE VARCHAR2,
        P_CUENTA_CONFIG VARCHAR2
    );

    PROCEDURE BORRAR_CUENTA(
        P_CUENTA_ID INTEGER
    );

END PLAN_DE_CUENTAS_PKG;