--------------------------------------------------------
-- Archivo creado  - lunes-julio-01-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_CUENTAS
--------------------------------------------------------

  CREATE TABLE "T_CUENTAS" 
   (	
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY start with 1001 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE, 
	"TITLE" VARCHAR2(80 BYTE), 
	"PARENT_ID" NUMBER, 
	"CUENTA_NUM" NUMBER 
   ) ;

   COMMENT ON COLUMN "T_CUENTAS"."FLG_GASTO" IS 'CUENTAS GASTOS';
   COMMENT ON COLUMN "T_CUENTAS"."FLG_BANCO" IS 'CUENTAS PARA DEPOSITOS';
   COMMENT ON COLUMN "T_CUENTAS"."INFO" IS 'BANCO_NUM';
REM INSERTING into T_CUENTAS
SET DEFINE OFF;
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('CAJA CHICA','111','1',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Compensacion','111','3',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Cheques Rechazados','113','3',null,'1',null,'1',null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('CAJA 3','111','12',null,null,'1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Cheques','113','1',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Venta de Productos Terminados','411','1',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('eCheques','113','2',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Materia Prima - Papel','117','1','1',null,null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Cta Cte Ventas','114','1',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Mercaderia de Reventa','117','3','1',null,null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Materia Prima - Planchas','117','2','1',null,null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Garrafas','511','7','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('CREDICOOP','112','1',null,'1','1','1','191-018-0000',to_date('01/01/2024','DD/MM/RRRR'),to_date('30/04/2024','DD/MM/RRRR'),null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('ICBC','112','2',null,'1','1','1','015-973-0000',to_date('01/12/2023','DD/MM/RRRR'),to_date('30/04/2024','DD/MM/RRRR'),null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('IVA Debito Fiscal','212','1',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion Ingresos Brutos','212','2',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Percepcion IVA','115','1',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Percepcion IIBB','115','2',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Cheques 2017','113','999',null,null,'1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('IVA credito Fiscal','115','3',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Deuda Provedores','211','1',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion Ganancias','118','1',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion IVA','118','2',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion Ingresos Brutos','118','3',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retenciones Patronales','118','4',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion Ganancias','215','1',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion Iva','215','2',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion IIBB','215','3',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('SIJP','215','5',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Energia Planta','511','6','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Intereses','514','1','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Servicio de Seguridad','512','10','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Sueldos Fabricacion','511','1','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Sueldos Administrativos','512','2','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Cesar','116','3',null,'1','1','1',null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Viaticos','512','11','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Tarjeta CABAL','119','3',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Seguridad e Higiene','515','1','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Sindicato','511','12','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('IVA a pagar','212','3',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retenciones Patronales','215','4',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Cargas Sociales','511','13','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Anticipo de Ganancias','515','2','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Bienes Personales','515','3','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Convenio Multilateral','515','4','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Aysa','512','3','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Tarjeta Visa ICBC','119','4',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Limpieza','512','4','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Grabados y Troqueles','117','4','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Insumos - Corrugado','511','2','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Insumos - Terminado','511','3','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Insumos - Palletizado','511','4','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Insumos - Mantenimiento','511','5','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Agua','512','5','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Libreria y Papeleria','512','6','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Desechos - Acumar','511','10','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Gastos Telefonia','512','7','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Comisiones','521','1','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Fletes','513','2','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Alquileres','513','3','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Descuenta IVA','111','11',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('CAJA GRANDE','111','2',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion SIRE','118','5',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Redondeo','111','4',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Trasferencias Diferidas','113','4',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Amilcar','116','1',null,'1','1','1',null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Carlos','116','2',null,'1','1','1',null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('servicio eventual','511','9','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Donaciones','522','1','1',null,null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Donaciones','513','4','1',null,null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Gastos Adm.(balance)','512','12','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Flota Automoviles','513','5','1',null,null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Gastos de Oficina','512','13','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Medicina prepaga','513','6','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Honorarios','512','14','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Willy','116','4',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Cheques Propios Entregados','216','1',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('eCheques Generados','216','2',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion SIRE','215','6',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Alpha','121','1',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion SUSS','215','7',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Ferreteria','511','8','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Moratoria Arba','515','5','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Impuesto Inmobiliario','515','6','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Seguros','511','11','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Contaduria','512','15','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retiro Socios','521','2','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Compras Particulares','523','1','1',null,null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Maquinaria','122','1',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Victoria','116','10',null,null,'1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Materiales','511','15','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retiro Socios','116','9',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion Municipal','215','8',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Retencion Municiapal','118','8',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values (Tarjetas','11','119',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Gastos Bancarios','513','1','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('SIRCREB','118','6',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('LEY 25413','118','7',null,'1',null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Metrogas','511','14','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values (Cierre de Ejercicio','12','124',null,null,null,null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Cierre de Banco','124','2',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Cierre de Caja','124','1',null,'1','1',null,null,null,null,null);
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Indumentaria','511','16','1','1',null,null,null,null,null,'1');
Insert into T_CUENTAS (TITLE,PARENT_ID,CUENTA_NUM) values ('Mensajeria','512','9','1','1',null,null,null,null,null,'1');
--------------------------------------------------------
--  DDL for Index T_CUENTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T_CUENTAS_PK" ON "T_CUENTAS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index T_CUENTAS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "T_CUENTAS_UK1" ON "T_CUENTAS" ("PARENT_ID", "CUENTA_NUM") 
  ;
--------------------------------------------------------
--  Constraints for Table T_CUENTAS
--------------------------------------------------------

  ALTER TABLE "T_CUENTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "T_CUENTAS" ADD CONSTRAINT "T_CUENTAS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "T_CUENTAS" ADD CONSTRAINT "T_CUENTAS_UK1" UNIQUE ("PARENT_ID", "CUENTA_NUM")
  USING INDEX  ENABLE;
