--------------------------------------------------------
-- Archivo creado  - viernes-junio-28-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_CAB_TIPO
--------------------------------------------------------

  CREATE TABLE "T_CAB_TIPO" 
   (	"ID" NUMBER, 
	"APEX_PAGINA" NUMBER, 
	"CTA" NUMBER, 
	"KEY" VARCHAR2(10 BYTE), 
	"COD_AFIP" NUMBER, 
	"TITLE" VARCHAR2(20 BYTE), 
	"SIGNO" NUMBER, 
	"LIBRO_COMPRAS" NUMBER, 
	"LIBRO_VENTAS" NUMBER, 
	"T_MODO" VARCHAR2(20 BYTE), 
	"T_TIPO" VARCHAR2(20 BYTE), 
	"SALDO_INICIAL" NUMBER(*,0), 
	"CUENTA_DEBE" NUMBER, 
	"CUENTA_HABER" NUMBER
   ) ;

   COMMENT ON COLUMN "T_CAB_TIPO"."LIBRO_COMPRAS" IS '1 SALE E NLIBRO';
REM INSERTING into LOA.T_CAB_TIPO
SET DEFINE OFF;
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1001',null,'1','S/INI','0','SALDO INICIAL','1',null,null,'VTA_FACTURAS','SALDO INICIAL','1',null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1002',null,'2','S/INI',null,'SALDO INICIAL','1',null,null,'VTA_REMITOS','SALDO INICIAL','1',null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2001',null,'1','S/INI',null,'SALDO INICIAL','1',null,null,'PROV_COMPRAS','SALDO INICIAL','1',null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2002',null,'2','S/INI',null,'SALDO INICIAL 2','1',null,null,'PROV_COMPRAS','SALDO INICIAL','1',null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1101',null,'1','Ped',null,'PEDIDO','1',null,null,null,null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1201',null,'1','Rto',null,'REMITO','1',null,null,'VTA_REMITOS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1210',null,'2','Rta',null,'REMITO','1',null,null,'VTA_REMITOS',null,null,'1008','1005');
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1211',null,'2','N/D',null,'NOTA DEBITO','1',null,null,'VTA_REMITOS',null,null,'1008','1003');
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1212',null,'2','N/C',null,'NOTA CREDITO 2','-1',null,null,'VTA_REMITOS',null,null,'1008','1005');
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1501',null,'1','FA','1','FACTURA A','1',null,null,'VTA_FACTURAS','FACTURA',null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1502',null,'1','NDA','2','N/ DEBITO A','1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1503',null,'1','NCA','3','N/ CREDITO A','-1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1519',null,'1','FC EXP','19','FACT EXPORT','1',null,null,'VTA_FACTURAS','FACTURA',null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1520',null,'1','ND EXP','20','N/ DEB  EXP','1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1521',null,'1','NC EXP','21','N/ CRED  EXP','-1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1506',null,'1','FB','6','FACTURA B ','1',null,null,'VTA_FACTURAS','FACTURA',null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1507',null,'1','NDB','7','N/ DEB B','1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1508',null,'1','NCB','8','N/ CRED B','-1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1601',null,'1','REC',null,'RECIBO','1',null,null,'VTA_RECIBOS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1602',null,'2','REC',null,'RECIBO','1',null,null,'VTA_RECIBOS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2501',null,'1','FA',null,'FACTURA A','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2502',null,'1','NDA',null,'NOTA DEBITO','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2503',null,'1','NCA',null,'NOTA CREDITO','-1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2504',null,'1','FB',null,'FACTURA B','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2505',null,'1','FC',null,'FACTURA C','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2506',null,'1','TFA',null,'TICKET FISCAL A','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2507',null,'1','TFB',null,'TICKET FISCAL B','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2508',null,'1','POLIZA',null,'POLIZA SEGURO','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2511',null,'1','RC',null,'RECIBO C','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2512',null,'1','FM',null,'FACTURA M','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2601',null,'1','O/P',null,'O PAGO','1',null,null,'PROV_PAGOS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2602',null,'2','O/P',null,'PAGO ','1',null,null,'PROV_PAGOS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2509',null,'1',null,null,'RECIBO ?','1',null,null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2210',null,'2','COMPRA',null,'COMPRA','1',null,null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2513',null,'1','CUOT',null,'CUOTA SINDICAL','1',null,null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2514',null,'1','CONV',null,'CONV. MULT ','1',null,null,null,null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2515',null,'1','ARBA',null,'ARBA','1',null,null,null,null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2516',null,'1','RET GCIA',null,'RET GCIAS','1',null,null,null,null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2518',null,'1','SEG SOC',null,'SEG SOCIAL','1',null,null,null,null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2519',null,'1','ANT GCIA',null,'ANT GCIAS','1',null,null,null,null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2520',null,'1','SICOS',null,'SICOS','1',null,null,null,null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2517',null,'1','IVA',null,'IVA','1',null,null,null,null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2521',null,'1','AP AFIL',null,'APOR AFILIADOS','1',null,null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2522',null,'1','AP SOLID',null,'APOR SOLIDARIOS','1',null,null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2523',null,'1','CAP TECN',null,'CAP TECNICA','1',null,null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1552',null,'1','NDE','202','NOTA DEB ELECT','1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1553',null,'1','NCE','203','NOTA CRED ELECT','-1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1551',null,'1','FCE','201','FAC CRED ELEC','1',null,null,'VTA_FACTURAS','FACTURA',null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2599',null,'1','CHQ RECH',null,'CHEQ RECH PROV','1','0',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1599',null,'1','ND CH RECH',null,'ND CHEQ RECH','1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1202',null,'1','Rto Dev',null,'DEVOLUCION','-1',null,null,'VTA_REMITOS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1213',null,'2','Rta Dev',null,'DEVOLUCION','-1',null,null,'VTA_REMITOS',null,null,'1008','1003');
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1598',null,'1','NC CH RECH',null,'NC GASTOS CHQ  RECH ','-1',null,null,'VTA_FACTURAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2212',null,'2','NDA',null,'NOTA DEBITO','1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2213',null,'2','NCA',null,'NOTA CREDITO','-1','1',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1000',null,'1','MOV',null,'MOVIMIENTO','1',null,null,'DOCS','MOV',null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('2598',null,'2','CHQ RECH',null,'CHEQ RECH PROV','1','0',null,'PROV_COMPRAS',null,null,null,null);
Insert into LOA.T_CAB_TIPO (ID,APEX_PAGINA,CTA,KEY,COD_AFIP,TITLE,SIGNO,LIBRO_COMPRAS,LIBRO_VENTAS,T_MODO,T_TIPO,SALDO_INICIAL,CUENTA_DEBE,CUENTA_HABER) values ('1215',null,'2','Ch Rech 2',null,'CHEQUE RECHAZADO 2','1',null,null,'VTA_REMITOS',null,null,'1008','1003');
--------------------------------------------------------
--  DDL for Index CAB_TIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LOA"."CAB_TIPO_PK" ON "LOA"."T_CAB_TIPO" ("ID") 
  ;
--------------------------------------------------------
--  Constraints for Table T_CAB_TIPO
--------------------------------------------------------

  ALTER TABLE "LOA"."T_CAB_TIPO" ADD CONSTRAINT "CAB_TIPO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "LOA"."T_CAB_TIPO" MODIFY ("ID" NOT NULL ENABLE);
