
-- TODO: MODIFICAR CAMPOS DE LA TABLA T_VTA_RECIBOS
/*
ALTER TABLE TT_VTA_RECIBOS RENAME COLUMN FECHA TO CBTEFCH;
ALTER TABLE TT_VTA_RECIBOS RENAME COLUMN PUNTO_VENTA TO PTOVTA;
ALTER TABLE TT_VTA_RECIBOS RENAME COLUMN nro_cab TO DOCNRO;
ALTER TABLE TT_VTA_RECIBOS RENAME COLUMN cli_dfiscal_id to DFISCAL_ID;
ALTER TABLE TT_VTA_RECIBOS RENAME COLUMN total to imptotal;
ALTER TABLE TT_VTA_RECIBOS RENAME COLUMN saldo to saldo_pendiente;
*/


-- crear vista encapsulamiento
CREATE OR REPLACE VIEW v_vta_recibos AS
    SELECT id
          ,cbtefch
          ,cta
          ,ptovta
          ,docnro
          ,cliente_id
          ,dfiscal_id
          ,cli_cuenta_id
          ,imptotal
          ,saldo_pendiente
          ,obs
          ,status
      FROM tt_vta_recibos;

-- revisar VISTAS Y FUNCIONES
--DOCS_TRG
--DOCS_CUENTA_BLOQ
>> VTA_RECIBOS
PC_RECIBOS
SALDOS_CLIENTES
PMPE_RECIBOS
TRG_VTA_RECIBOS_NEW
TRG_VTA_RECIBOS_UPD
X20_JOB1
RECIBOS_PKG
SALDO_CLIENTE2

-- COMPLETAR PACKAGE RECIBOS_PKG

--> REEMPLAZAR FUNCIONT APPLY_REC -- RECIBOS_PKG.SALDO_APLICADO

--> ELIMITAR VISTA T_VTA_RECIBOS Y RENOMBRAR TABLA TT