--------------------------------------------------------
--  File created - lunes-junio-03-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "T_USER_ROLES" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITLE" VARCHAR2(4000 CHAR), 
	"IS_ACTIVE" VARCHAR2(1 CHAR) DEFAULT 'Y'
   ) ;
--------------------------------------------------------
--  DDL for Index T_USER_ROLES_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T_USER_ROLES_ID_PK" ON "T_USER_ROLES" ("ID") 
  ;
--------------------------------------------------------
--  Constraints for Table T_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "T_USER_ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "T_USER_ROLES" ADD CONSTRAINT "T_USER_ROLES_IS_ACTIVE" CHECK (is_active IN('Y','N')) ENABLE;
  ALTER TABLE "T_USER_ROLES" ADD CONSTRAINT "T_USER_ROLES_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "T_USER_ROLES" MODIFY ("TITLE" NOT NULL ENABLE);
