--------------------------------------------------------
--  File created - lunes-junio-03-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_USER_APPLYS
--------------------------------------------------------

  CREATE TABLE "T_USER_APPLYS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_ID" NUMBER, 
	"ROLE_ID" NUMBER, 
	"APP_ID" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Index T_USER_APPLYS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T_USER_APPLYS_ID_PK" ON "T_USER_APPLYS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index T_USER_APPLYS_I1
--------------------------------------------------------

  CREATE INDEX "T_USER_APPLYS_I1" ON "T_USER_APPLYS" ("USER_ID") 
  ;
--------------------------------------------------------
--  DDL for Index T_USER_APPLYS_I2
--------------------------------------------------------

  CREATE INDEX "T_USER_APPLYS_I2" ON "T_USER_APPLYS" ("ROLE_ID") 
  ;
--------------------------------------------------------
--  Constraints for Table T_USER_APPLYS
--------------------------------------------------------

  ALTER TABLE "T_USER_APPLYS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "T_USER_APPLYS" ADD CONSTRAINT "T_USER_APPLYS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_USER_APPLYS
--------------------------------------------------------

  ALTER TABLE "T_USER_APPLYS" ADD CONSTRAINT "T_USER_APPLYS_USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "T_USERS" ("ID") ENABLE;
  ALTER TABLE "T_USER_APPLYS" ADD CONSTRAINT "T_USER_APPLYS_ROLE_ID_FK" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "T_USER_ROLES" ("ID") ENABLE;
