--------------------------------------------------------
--  File created - lunes-junio-03-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_USERS
--------------------------------------------------------

  CREATE TABLE "T_USERS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(4000 CHAR), 
	"PASSWORD" VARCHAR2(4000 CHAR), 
	"IS_ACTIVE" VARCHAR2(1 CHAR), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(75 BYTE), 
	"VALID_PASSWORD" VARCHAR2(1 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Index T_USERS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T_USERS_ID_PK" ON "T_USERS" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index T_USERS_TITLE_UNQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "T_USERS_TITLE_UNQ" ON "T_USERS" ("USERNAME") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C0012781
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0012781" ON "T_USERS" ("EMAIL") 
  ;
--------------------------------------------------------
--  Constraints for Table T_USERS
--------------------------------------------------------

  ALTER TABLE "T_USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "T_USERS" ADD CONSTRAINT "T_USERS_IS_ACTIVE" CHECK (is_active IN('Y','N')) ENABLE;
  ALTER TABLE "T_USERS" ADD CONSTRAINT "CK_MAIL" CHECK (regexp_like(email, '^(\S+)\@(\S+)\.(\S+)$')) ENABLE;
  ALTER TABLE "T_USERS" ADD CONSTRAINT "T_USERS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "T_USERS" ADD CONSTRAINT "T_USERS_TITLE_UNQ" UNIQUE ("USERNAME")
  USING INDEX  ENABLE;
  ALTER TABLE "T_USERS" ADD UNIQUE ("EMAIL")
  USING INDEX  ENABLE;
