CREATE TABLE T_DOC_TIPOS(
    ID NUMBER NOT NULL ENABLE,
    DOC_MODO NUMBER NOT NULL ENABLE, --> 1 CAJA / 2 CHEQUES TERCEROS / 3 CHEQUES PROPIOS / 4 RETENCIONES
    TITLE VARCHAR2(80),
    KEY VARCHAR2(10),
    CONSTRAINT T_DOC_TIPOS_PK PRIMARY KEY (ID) USING INDEX ENABLE
);

/

CREATE TABLE T_DOCS (
    ID NUMBER NOT NULL ENABLE,
    DOC_MODO NUMBER NOT NULL ENABLE, --> 1 CAJA / 2 CHEQUES TERCEROS / 3 CHEQUES PROPIOS / 4 RETENCIONES
    DOC_TIPO_ID NUMBER NOT NULL ENABLE,
    DOC_FECHA DATE,
    DOC_IMPORTE NUMBER(*, 2) NOT NULL ENABLE,
    DOC_CTA NUMBER NOT NULL ENABLE,
    DOC_OBS VARCHAR2(200),
    VENTAS_RECIBO_ID NUMBER,
    COMPRAS_PAGO_ID NUMBER,
    PC_CUENTA_IN NUMBER,
    PC_FECHA_IN DATE,
    PC_CUENTA_OUT NUMBER,
    PC_FECHA_OUT DATE,
    CHQ_KEY NUMBER,
    CHQ_NUMERO NUMBER,
    CHQ_BANCO VARCHAR2(20),
    CHQ_CUENTA VARCHAR2(20),
    CHQ_CUIT VARCHAR2(20),
    CHQ_RSOCIAL VARCHAR2(200),
    CHQ_FECHA_VENC DATE,
    CHQ_NOALAORDEN NUMBER,
    CREATED DATE,
    CREATED_BY VARCHAR2(20),
    UPDATED DATE,
    UPDATED_BY VARCHAR2(20),
    CONSTRAINT T_DOCS_PK PRIMARY KEY (ID) USING INDEX ENABLE
);

/

CREATE SEQUENCE DOCS_SEQ START WITH 1000 CACHE 10;

/

CREATE TRIGGER DOCS_TRG1 BEFORE
    INSERT ON T_DOCS FOR EACH ROW
BEGIN
    SELECT
        DOCS_SEQ.NEXTVAL INTO:NEW.ID
    FROM
        SYS.DUAL;
    :NEW.CREATED :=SYSDATE;
    :NEW.CREATED_BY :=NVL(V('APP_USER'), USER);
END;