create directory DP as '/home/oracle/DP';

-- > Copiar Archivo desde otro servidor
--  scp -P 1599 oracle@179.41.5.74:/media/oracle/padron.txt .

-- Crear tabla externa
CREATE TABLE te_dfiscales(
    cuit            CHAR(11 BYTE)
    ,title           CHAR(30 BYTE)
    ,imp_ganancias   CHAR(2 BYTE)
    ,imp_iva         CHAR(2 BYTE)
    ,monotributo     CHAR(2 BYTE)
    ,integrante_soc  CHAR(1 BYTE)
    ,empleador       CHAR(1 BYTE)
    ,act_monotributo CHAR(2 BYTE)
)
ORGANIZATION EXTERNAL(TYPE oracle_loader
    DEFAULT DIRECTORY dp ACCESS PARAMETERS(
        RECORDS DELIMITED BY NEWLINE
        FIELDS(
            cuit CHAR(11)
        ,title CHAR(30)
        ,imp_ganancias CHAR(2)
        ,imp_iva CHAR(2)
        ,monotributo CHAR(2)
        ,integrante_soc CHAR(1)
        ,empleador CHAR(1)
        ,act_monotributo CHAR(2)
        )
    )LOCATION(dp : 'padron.txt')
)REJECT LIMIT UNLIMITED;

/

-- tabla t_dfiscales
create table t_dfiscales (
    ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE,
    title                          varchar2(400 char),
    cuit                           varchar2(11 char),
    domicilio                      varchar2(400 char),
    ciudad                         varchar2(80 char),
    cp                             varchar2(10 char),
    provincia_id                   number,
    partido_id                     number,
    tipo_persona                   number,
    IMP_GANANCIAS                  varchar2(2 char),
    IMP_IVA                        varchar2(2 char),
    MONOTRIBUTO                    varchar2(2 char),
    INTEGRANTE_SOC                 varchar2(1 char),
    EMPLEADOR                      varchar2(1 char),
    ACT_MONOTRIBUTO                varchar2(2 char),
    cliente_id number,
    provedor_id number,
    empleado_id number,   
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
);

CREATE UNIQUE INDEX "T_DFISCALES_CUIT_PK" ON "T_DFISCALES"("CUIT");
/
create or replace trigger t_dfiscales_biu
    before insert or update
    on t_dfiscales
    for each row
declare 
    v_id number;
    v_cuit varchar2(11);
begin
    :NEW.CUIT := REPLACE(:NEW.CUIT,'-','');

    IF DFISCALES_PKG.VALIDAR_CUIT(:NEW.CUIT) < 0 THEN
        RAISE_APPLICATION_ERROR(-20000,'CUIT INVALIDO');
    END IF;
    
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);


end t_dfiscales_biu;
/

-- view 
create OR REPLACE view dfiscales as
SELECT
    id
   ,title
   ,cuit
   ,domicilio
   ,ciudad
   ,cp
   ,provincia_id
   ,partido_id
   ,tipo_persona
   ,imp_ganancias
   ,imp_iva
   ,monotributo
   ,integrante_soc
   ,empleador
   ,act_monotributo
   ,CLIENTE_ID
   ,PROVEDOR_ID
   
FROM
    t_dfiscales;

/    
