CREATE TABLE T_COMPRAS_APPLYS(
    ID             NUMBER NOT NULL ENABLE
    ,COMPRAS_CBTE_ID  NUMBER
    ,COMPRAS_PAGO_ID NUMBER
    ,IMPORTE        NUMBER
    ,CREATED        DATE
    ,CREATED_BY     VARCHAR2(20 BYTE)
    ,CONSTRAINT "COMPRAS_APPLYS_PK" PRIMARY KEY("ID")    ENABLE
    ,CONSTRAINT "COMPRAS_APPLYS_FK1" FOREIGN KEY("COMPRAS_CBTE_ID") REFERENCES T_COMPRAS_CBTES(ID)    ENABLE
    ,CONSTRAINT "COMPRAS_APPLYS_FK2" FOREIGN KEY("COMPRAS_PAGO_ID") REFERENCES T_COMPRAS_PAGOS(ID)    ENABLE
)
/

create SEQUENCE compras_applys_seq cache 10;

/

create or replace TRIGGER "T_COMPRAS_APPLYS_TRG" BEFORE INSERT ON "T_COMPRAS_APPLYS"
  FOR EACH ROW
BEGIN
    :NEW.CREATED    :=SYSDATE;
    :NEW.CREATED_BY := NVL(V('APP_USER'),USER);
    IF :NEW.ID IS NULL THEN
      SELECT compras_applys_seq.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
END;
